<?php
//
//  Generated by Chef. Do not hand edit
//

namespace RitsemaBanck;

use mysqli;

class ConnectDB
{
    private $servername = "<%= node['mysql']['host'] %>";
    private $username = "<%= node['mysql']['user'] %>";
    private $password = "<%= node['mysql']['password'] %>";
    private $database = "<%= node['mysql']['database'] %>";
    private $conn;

    public function __construct()
    {
        $this->conn = new MySQLi($this->servername, $this->username, $this->password, $this->database);
    }

    public function getConnection()
    {
        return $this->conn;
    }
}
